name: srgan-qr-code
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - pillow
  - matplotlib
  - pyyaml
  - jupyterlab
  - ipykernel
  - pip=24.0
  - pip:
      - qrcode[pil]
      - tensorflow[and-cuda]
      - tqdm
